#!MC 1120
# Created by Tecplot 360 build 11.2-0-563
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP IMAGEWIDTH = 600
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = 'cylinder.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
